name: Call a reusable workflow

on: workflow_dispatch
  
jobs:
  # call-workflow:
  #   uses: p-gombola/reusableworkflow/.github/workflows/workflow-A.yml@main
  #   with:
  #     who-to-greet: "George Jetson"
  before-call:
    runs-on: ubuntu-latest
    steps:
      - name: before
        run: |
          pwd
          ls
        shell: bash
  call-local-action:
    uses: p-gombola/external-reusableworkflow/.github/workflows/Greet.yaml@main
