name: Call a reusable workflow

on: workflow_dispatch
  
jobs:
  # call-workflow:
  #   uses: p-gombola/reusableworkflow/.github/workflows/workflow-A.yml@main
  #   with:
  #     who-to-greet: "George Jetson"
  call-local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
