name: Call a reusable workflow

on: workflow_dispatch
  
jobs:
  call-workflow:
    uses: p-gombola/reusableworkflow/.github/workflows/workflow-A.yml@main
    with:
      who-to-greet: "George Jetson"
