name: Workflow A

on: 
  workflow_call:
    inputs:
      who-to-greet:
        required: true
        type: string
        default: world
    
jobs:
  Nested:
    uses: p-gombola/reusableworkflow/.github/workflows/workflow-B.yml@main
    with: 
      who-to-greet: ${{inputs.who-to-greet}}


