name: Workflow B

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: world

jobs:
  Nested-C:
    uses: p-gombola/reusableworkflow/.github/workflows/workflow-C.yml@main
    with: 
      who-to-greet: ${{inputs.who-to-greet}}
