name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: world

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }}!"
