name: Workflow C

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        default: world

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }} from C!"
  Nested-D:
    uses: p-gombola/reusableworkflow/.github/workflows/workflow-D.yaml@main
    with: 
      who-to-greet: ${{inputs.who-to-greet}}
